package son32map;
import com.ochafik.lang.jnaerator.runtime.Structure;
import com.sun.jna.NativeLong;
/**
 * <i>native declaration : Son.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class TFilterMask extends Structure<TFilterMask, TFilterMask.ByValue, TFilterMask.ByReference > {
	/// private flags used by the marker filering
	public NativeLong lFlags;
	/**
	 * set of masks for each layer<br>
	 * C type : TLayerMask[4]
	 */
	public byte[] aMask = new byte[32 * 4];
	public TFilterMask() {
		super();
		initFieldOrder();
	}
	protected void initFieldOrder() {
		setFieldOrder(new java.lang.String[]{"lFlags", "aMask"});
	}
	/**
	 * @param lFlags private flags used by the marker filering<br>
	 * @param aMask set of masks for each layer<br>
	 * C type : TLayerMask[4]
	 */
	public TFilterMask(NativeLong lFlags, byte aMask[]) {
		super();
		this.lFlags = lFlags;
		if (aMask.length != this.aMask.length) 
			throw new IllegalArgumentException("Wrong array size !");
		this.aMask = aMask;
		initFieldOrder();
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected TFilterMask newInstance() { return new TFilterMask(); }
	public static TFilterMask[] newArray(int arrayLength) {
		return Structure.newArray(TFilterMask.class, arrayLength);
	}
	public static class ByReference extends TFilterMask implements Structure.ByReference {
		
	};
	public static class ByValue extends TFilterMask implements Structure.ByValue {
		
	};
}
