package son32map;
import com.ochafik.lang.jnaerator.runtime.Structure;
/**
 * <i>native declaration : Son.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class TSONCreator extends Structure<TSONCreator, TSONCreator.ByValue, TSONCreator.ByReference > {
	/**
	 * application identifier<br>
	 * C type : char[8]
	 */
	public byte[] acID = new byte[(8)];
	public TSONCreator() {
		super();
		initFieldOrder();
	}
	protected void initFieldOrder() {
		setFieldOrder(new java.lang.String[]{"acID"});
	}
	/**
	 * @param acID application identifier<br>
	 * C type : char[8]
	 */
	public TSONCreator(byte acID[]) {
		super();
		if (acID.length != this.acID.length) 
			throw new IllegalArgumentException("Wrong array size !");
		this.acID = acID;
		initFieldOrder();
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected TSONCreator newInstance() { return new TSONCreator(); }
	public static TSONCreator[] newArray(int arrayLength) {
		return Structure.newArray(TSONCreator.class, arrayLength);
	}
	public static class ByReference extends TSONCreator implements Structure.ByReference {
		
	};
	public static class ByValue extends TSONCreator implements Structure.ByValue {
		
	};
}
